### ISSUE TITLE
type error: random error untu , nange gothilla solve madlikke so assigning it to adithya Rao

### ISSUE THREAD

**Issue by AnirudhKaranth** [AnirudhKaranth/video-chat#2]
random error untu , nange gothilla solve madlikke so assigning it to adithya Rao

**Comment by Adithya11811** [comment]
hello, hello brother assign this issue to me

**Comment by Adithya11811** [comment]
@AnirudhKaranth  assign

**Comment by AnirudhKaranth** [comment]
He completed It. Nice Guy
